=== admire93/play/ext/playlist.dtd
<!ELEMENT playlist (file*)>
<!ATTLIST playlist
    name                CDATA   #REQUIRED
    basedir             CDATA   #REQUIRED
>

<!ELEMENT file EMPTY>
<!ATTLIST file
    src             CDATA   #REQUIRED
>

=== admire93/play/system/private/19/songlist.xml
<?xml version="1.0" encoding="ISO-8859-1" ?><!DOCTYPE playlist SYSTEM "http://play.0pen.us/ext/xml/playlist.dtd"><playlist name="" basedir="" xmlns="http://play.0pen.us/ext/xml/dtd/"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/background1.png"></playlist><?xml version="1.0" encoding="ISO-8859-1" ?><!DOCTYPE playlist SYSTEM "http://play.0pen.us/ext/xml/playlist.dtd"><playlist name="" basedir="" xmlns="http://play.0pen.us/ext/xml/dtd/"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/background1.png"></playlist><?xml version="1.0" encoding="ISO-8859-1" ?><!DOCTYPE playlist SYSTEM "http://play.0pen.us/ext/xml/playlist.dtd"><playlist name="" basedir="" xmlns="http://play.0pen.us/ext/xml/dtd/"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/background1.png"></playlist><?xml version="1.0" encoding="ISO-8859-1" ?><!DOCTYPE playlist SYSTEM "http://play.0pen.us/ext/xml/playlist.dtd"><playlist name="" basedir="" xmlns="http://play.0pen.us/ext/xml/dtd/"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/background1.png"></playlist><?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE playlist SYSTEM "http://play.0pen.us/ext/xml/playlist.dtd"><playlist name="" basedir="" xmlns="http://play.0pen.us/ext/xml/dtd/"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/background1.png"></playlist><?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE playlist SYSTEM "http://play.0pen.us/ext/xml/playlist.dtd"><playlist name="" basedir="" xmlns="http://play.0pen.us/ext/xml/dtd/"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/hit.png"><file src="/home/admire/play/system/upload/background1.png"></playlist><?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE playlist SYSTEM "http://play.0pen.us/ext/xml/playlist.dtd"><playlist name="" basedir="" xmlns="http://play.0pen.us/ext/xml/dtd/">
